# TAKE HOME LAB EXERCISE - 01

-----------

**(1).Create a 1D array with 10 values in it and then convert the 1D array to 2D array ?**

In [1]:
import numpy as np
np.array(range(0,10)).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

-------------------------------------------------------------

**(2).Print or show only 3 decimal places of the numpy array `random_arr`**

In [2]:
random_arr=np.random.random([10])
np.set_printoptions(precision=3)
random_arr

array([0.615, 0.635, 0.313, 0.879, 0.443, 0.155, 0.439, 0.655, 0.417,
       0.488])

----------------------------------

**(3).The number of items printed to be limit in python numpy array a to a maximum of 6 elements.**

   
     Intake : x = np.arange(15)
               array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])
               
     Result : ([ 0,  1,  2, ..., 12, 13, 14])

In [11]:
x=np.arange(15)
np.set_printoptions(threshold=6)
x

array([ 0,  1,  2, ..., 12, 13, 14])

---------------------

**(4). Take two arrays  `x` and `y` and Stack the `x` and `y` arrays Horizontal.**


    Intake:
                x = np.arange(10).reshape(2,-1)

                y = np.repeat(1, 10).reshape(2,-1)

 
    
    Result:       ([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
                   [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [3]:
x = np.arange(10).reshape(2,-1)
y = np.repeat(1, 10).reshape(2,-1)
Result=np.hstack([x,y])
Result

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

----------------------

**(5). Consider the given array's and print the values which are common in both the arrays.**
    
    
    Intake: 
   
        x = np.array([1,2,3,2,3,4,3,4,5,6])
        y = np.array([7,2,10,2,7,4,9,4,9,8])
 
    Results:
        
         ([2, 4])
            
    

In [4]:
x = np.array([1,2,3,2,3,4,3,4,5,6])
y = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(x,y)

array([2, 4])

---------------------

**(6). There are two array x and y ,drop the items in `X` which already exist in `Y`.**

   
    INTAKE:
     x = np.array([1,2,3,4,5])
     y = np.array([5,6,7,8,9])
    
    
    RESULT:
     ([1,2,3,4])
        
    

In [5]:
array1 = np.array([1,2,3,4,5])
array2 = np.array([5,6,7,8,9])
np.setdiff1d(array1, array2)

array([1, 2, 3, 4])

--------------------------

**(7). Reverse the rows of a 2D array.**


    Intake : X = np.arange(9).reshape(3,3)
    
    Result :      ([[6, 7, 8],
                    [3, 4, 5],
                    [0, 1, 2]])

In [6]:
X = np.arange(9).reshape(3,3)
np.flip(X,axis=0)

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

----------------------

**(8). Reverse the columns of a 2D array.**

    Intake : X = np.arange(9).reshape(3,3)
    
    Result :     ([[2, 1, 0],
                   [5, 4, 3],
                   [8, 7, 6]])


In [7]:
X = np.arange(9).reshape(3,3)
np.flip(X,axis=1)

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

---------------------

**(9). Print the ranks for the given numeric array `x`.**
 
   
    Intake:
    np.random.seed(10)
    x = np.random.randint(20, size=10)
    print(x)
    [ 9  4 15  0 17 16 17  8  9  0]
    
    
    Result:
    [4 2 6 0 8 7 9 3 5 1]
    

In [8]:
np.random.seed(10)
x = np.random.randint(20, size=10)
arg_x1=(x.argsort()).argsort()
print(x)
print(arg_x1)

[ 9  4 15  0 17 16 17  8  9  0]
[4 2 6 0 8 7 9 3 5 1]


--------------------

**(10). For the given numeric array print the rank array with same shape of numeric array.**


    Intake:
    np.random.seed(10)
    x = np.random.randint(20, size=[2,5])
    print(a)
    [[ 9  4 15  0 17]
    [16 17  8  9  0]]
    
    Result:
    [[4 2 6 0 8]
    [7 9 3 5 1]]

In [9]:
np.random.seed(10)
x = np.random.randint(20, size=[2,5])
print(x)
x_arg=(((x.flatten()).argsort()).argsort()).reshape(2,5)
print(x_arg)

[[ 9  4 15  0 17]
 [16 17  8  9  0]]
[[4 2 6 0 8]
 [7 9 3 5 1]]


--------------------------------

**(11). Subtract the 1d array y_1d from the 2d array x_2d, such that each item of y_1d subtracts from respective row of x_2d.**
    
    Intake:
    x_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
    y_1d = np.array([1,2,3])
    
    Result:
     [[2 2 2]
     [2 2 2]
     [2 2 2]]

In [10]:
x_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
y_1d = np.array([1,2,3])
y_trans=y_1d.reshape(3,1)
diff=np.subtract(x_2d,y_trans)
print(diff)

[[2 2 2]
 [2 2 2]
 [2 2 2]]


----------------

# ----------------------------------HAPPY LEARNING--------------------------------------------------

-------------------